article/urls.py
from django.urls import path
from .views import articles, article_detail, article_by_category, set_language

app_name = 'article'

urlpatterns = [
    path('', articles, name='articles'),
    path('<slug:article_slug>/', article_detail, name='article_detail'),
    path('kategori/<slug:category_slug>', article_by_category, name='article_by_category'),
    path("set_language/<str:language>", set_language, name="set-language"),
]

base/urls.py
from django.urls import path
from .views import index, about, contact, error, galeries

app_name = 'base'

urlpatterns = [
    path('', index, name='index'),
    path('hakkimizda/', about, name='about'),
    path('galeri/', galeries, name='galeries'),
    path('iletisim/', contact, name='contact'),
    path('error/', error, name='error'),
]

core/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from base.views import error

handler = error

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += i18n_patterns(
    path('', include('base.urls', namespace='base')),
    path('makale/', include('article.urls', namespace='article')),
    path('ders/', include('lesson.urls', namespace='lesson')),
    path('rosetta/', include('rosetta.urls')),
    prefix_default_language=False,
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lesson/urls.py
from django.urls import path
from .views import *

app_name = 'lesson'

urlpatterns = [
    path('', lessons, name='lessons'),
    path('<slug:lesson_slug>', lesson_detail, name='lesson_detail'),
]

base/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.utils.text import slugify

class GeneralItem(models.Model):
    title = models.CharField(max_length=100, verbose_name = 'Site Adı')
    description = RichTextField(verbose_name = 'Açıklama')
    email = models.EmailField(verbose_name = 'E-posta')
    address = RichTextField(verbose_name = 'Adres')
    main_phone_number = models.CharField(max_length = 50, verbose_name = 'En çok kullanılan telefon numarası', null=True, blank=True)
    favicon = models.ImageField(upload_to = 'favicon', verbose_name = 'Favicon')
    navbar_img = models.ImageField(upload_to='navbar_img', verbose_name = 'Navbar Resmi')
    footer_img = models.ImageField(upload_to='footer_img', verbose_name = 'Footer Resmi')
    facebook = models.URLField(verbose_name = 'Facebook linki', null=True, blank=True)
    instagram = models.URLField(verbose_name = 'İnstagram linki', null=True, blank=True)
    twitter = models.URLField(verbose_name = 'Twitter linki', null=True, blank=True)
    youtube_1 = models.URLField(verbose_name = 'Youtube birinci linki', null=True, blank=True)
    youtube_2 = models.URLField(verbose_name = 'Youtube ikinci linki', null=True, blank=True)
    youtube_3 = models.URLField(verbose_name = 'Youtube üçüncü linki', null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name = 'Olusturulma Tarihi')
    
    def __str__(self):
        return self.title
    
    class Meta:
        verbose_name_plural = 'Genel Bilgiler'
 

class HomeSlider(models.Model):
    text_arabic = RichTextField(verbose_name = 'Metin (Arapça)')
    text_translation =  RichTextField(verbose_name = 'Metin (Çeviri)')
    source = models.CharField(max_length = 200, verbose_name = 'Kaynak')
    image = models.ImageField(upload_to = 'home_slider', verbose_name = 'Resim')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name = 'Olusturulma Tarihi')
    
    def __str__(self):
        return self.source

    class Meta:
        verbose_name_plural = 'Ana Sayfa Sliderları'



class PageBanner(models.Model):
    title = models.CharField(max_length = 200, verbose_name = 'Banner Baslığı')
    
    about_title = models.CharField(max_length = 200, verbose_name = 'Hakkımızda Banner Başlığı')
    about_img = models.ImageField(upload_to='about_banner_img', verbose_name = 'Hakkımızda Banner Resmi')
    about_arabic_text = RichTextField(verbose_name = 'Hakkımızda Banner Metin (Arapça)')
 
    article_title = models.CharField(max_length = 200, verbose_name = 'Makale Banner Başlığı')
    article_img = models.ImageField(upload_to='article_banner_img', verbose_name = 'Makale Banner Resmi')
    article_arabic_text = RichTextField(verbose_name = 'Makale Banner Metin (Arapça)')
    
    article_category_title = models.CharField(max_length = 200, verbose_name = 'Makale Kategorisi Banner Başlığı')
    article_category_img = models.ImageField(upload_to='article_category_banner_img', verbose_name = 'Makale Kategorisi Banner Resmi')
    article_category_arabic_text = RichTextField(verbose_name = 'Makale Kategorisi Banner Metin (Arapça)')
    
    article_detail_title = models.CharField(max_length = 200, verbose_name = 'Makale Detayları Banner Başlığı')
    article_detail_img = models.ImageField(upload_to='article_detail_banner_img', verbose_name = 'Makale Detayları Banner Resmi')
    article_detail_arabic_text = RichTextField(verbose_name = 'Makale Detayları Banner Metin (Arapça)')

    lesson_title = models.CharField(max_length = 200, verbose_name = 'Ders Banner Başlığı')
    lesson_img = models.ImageField(upload_to='lesson_banner_img', verbose_name = 'Ders Banner Resmi')
    lesson_arabic_text = RichTextField(verbose_name = 'Ders Banner Metin (Arapça)')
    
    lesson_detail_title = models.CharField(max_length = 200, verbose_name = 'Ders Detayları Banner Başlığı')
    lesson_detail_img = models.ImageField(upload_to='lesson_detail_banner_img', verbose_name = 'Ders Detayları Banner Resmi')
    lesson_detail_arabic_text = RichTextField(verbose_name = 'Ders Detayları Banner Metin (Arapça)')
    
    galery_title = models.CharField(max_length = 200, verbose_name = 'Galeri Banner Başlığı')
    galery_img = models.ImageField(upload_to='galery_banner_img', verbose_name = 'Galeri Banner Resmi')
    galery_arabic_text = RichTextField(verbose_name = 'Galeri Banner Metin (Arapça)')
    
    contact_title = models.CharField(max_length = 200, verbose_name = 'İletişim Banner Başlığı')
    contact_img = models.ImageField(upload_to='contact_banner_img', verbose_name = 'İletişim Banner Resmi')
    contact_arabic_text = RichTextField(verbose_name = 'İletişim Banner Metin (Arapça)')
    
    subcsribe_title = models.CharField(max_length = 200, verbose_name = 'Abone Ol Banner Başlığı')
    subcsribe_img = models.ImageField(upload_to='subscribe_banner_img', verbose_name = 'Abone Ol Banner Resmi')
    subcsribe_description = models.TextField(verbose_name = 'Abone Ol Banner Kısa Açıklaması')
    
    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = 'Sayfa Bannerları'
        

class Phone(models.Model):
    title = models.CharField(max_length = 200, verbose_name = 'Telefon Numarası Başlığı')
    phone_number = models.CharField(max_length = 50, verbose_name = 'Telefon numarası')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name = 'Olusturulma Tarihi')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = 'Telefon Numaraları'
        
        
class IslamicConditions(models.Model):
    title = models.CharField(max_length=200, verbose_name = 'Şartın Başlığı')
    description = RichTextField(verbose_name = 'Şartın Açıklaması')
    icon = models.CharField(max_length=200, verbose_name = 'Şartın Simgesi (İkon)')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name = 'Olusturulma Tarihi')
    
    def __str__(self):
        return self.title
    
    class Meta:
        verbose_name_plural = 'İslamın Şartları'
        
        
class About(models.Model):
    title = models.CharField(max_length = 300, verbose_name = 'Hakkımızda Başlığı')
    description = RichTextField(verbose_name = 'Hakkımızda Açıklaması')
    image = models.ImageField(upload_to = 'about', verbose_name = 'Arkaplan Resmi')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name = 'Olusturulma Tarihi')
    
    class Meta:
        verbose_name_plural = 'Hakkımızda'
        
    def __str__(self):
        return self.title
    
class Mission(models.Model):
    title = models.CharField(max_length = 300, verbose_name = 'Görevler Başlığı')
    description = RichTextField(verbose_name = 'Açıklama')
    image = models.ImageField(upload_to = 'mission', verbose_name = 'Resim')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name = 'Olusturulma Tarihi')
    
    def __str__(self):
        return self.title
    
    class Meta:
        verbose_name_plural = 'Görevler'
    
    
class SubMission(models.Model):
    mission = models.ForeignKey(Mission, on_delete = models.CASCADE, verbose_name = 'Görevler', related_name = 'submissions')
    title = models.CharField(max_length = 400, verbose_name = 'Görevler Başlığı')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name = 'Olusturulma Tarihi')
    
    def __str__(self):
        return self.title
    
    class Meta:
        verbose_name_plural = 'Alt Görevler'
        
        
class Subscribe(models.Model):
    email = models.EmailField(verbose_name = 'E-posta')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name = 'Olusturulma Tarihi')

    def __str__(self):
        return self.email

    class Meta:
        verbose_name_plural = 'Aboneler'
        

class Contact(models.Model):
    name = models.CharField(max_length=200, verbose_name='Ad Soyad')
    email = models.EmailField(verbose_name='E-posta')
    phone = models.CharField(max_length=50, verbose_name='Telefon Numarası')
    subject = models.CharField(max_length=300, verbose_name='Konu')
    message = models.TextField(verbose_name='Mesaj')
    is_reply = models.BooleanField(default=False, verbose_name='Cevaplandı mı?', null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Mesaj Geliş Tarihi')
    
    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name_plural = 'İletişim'
        
        
class Galery(models.Model):
    title = models.CharField(max_length = 300, verbose_name = 'Başlık')
    image = models.ImageField(upload_to='images/', verbose_name='Resim')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')
    
    def __str__(self):
        return self.title
    
    class Meta:
        verbose_name_plural = 'Galeri'
        
class MetaTag(models.Model):
    META_NAME_CHOICES = [
        ("author", "Yazar"),
        ("description", "Açıklama"),
        ("keywords", "Anahtar Kelimeler"),
        ("robots", "Robots"),
        ("viewport", "Viewport"),
        ("og:title", "Open Graph Başlığı"),
        ("og:description", "Open Graph Açıklaması"),
        ("og:image", "Open Graph Görseli"),
        ("twitter:title", "Twitter Başlığı"),
        ("twitter:description", "Twitter Açıklaması"),
        ("twitter:image", "Twitter Görseli"),
    ]
    
    page_name = models.CharField(max_length=255, help_text="Ana sayfa için boş bırakınız. Sayfa adı (örnek: Hakkımızda, Servis, Blog, Galeri, İletişim)", blank=True, null=True)
    slug = models.SlugField(blank=True, null=True)
    name = models.CharField(max_length=50, choices=META_NAME_CHOICES, help_text="Meta adı veya özelliği")
    content = models.TextField(help_text="Meta tag içeriği (content)")
    
    def save(self, *args, **kwargs):
        if not self.page_name:
            self.slug = ""
        if not self.slug or self.slug != slugify(self.page_name):

base/forms.py
from django import forms
from .models import Subscribe
from .models import Contact

class SubscribeForm(forms.ModelForm):
    class Meta:
        model = Subscribe
        fields = ['email']
        widgets = {
            "email": forms.EmailInput(
                attrs={
                    "placeholder": "Mail Adresinizi Girin",
                }
            )
        }

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['name', 'email', 'phone', 'subject', 'message']
        widgets = {
            'name': forms.TextInput(attrs={
                'placeholder': 'İsim ve Soyisminiz',
                'class': 'form-control mb-3'
            }),
            'email': forms.EmailInput(attrs={
                'placeholder': 'Mail Adresiniz',
                'class': 'form-control mb-3'
            }),
            'phone': forms.TextInput(attrs={
                'placeholder': 'Telefon Numarası',
                'class': 'form-control mb-3 phone-mask',
            }),
            'subject': forms.TextInput(attrs={
                'placeholder': 'Mesajın Konusu',
                'class': 'form-control mb-3'
            }),
            'message': forms.Textarea(attrs={
                'placeholder': 'Mesajınız',
                'class': 'form-control mb-3'
            })
        }

base/views.py
from django.shortcuts import render
from .forms import SubscribeForm, ContactForm
from django.shortcuts import redirect
from django.contrib import messages
from .models import Galery
from django.core.paginator import Paginator

def index(request):
    
    if request.method == "POST":
        form = SubscribeForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Başarıyla abone olundu!!!")
            return redirect('base:index')
    else:
        form = SubscribeForm()
        
    context = {
        'form' : form
    }
    
    return render(request, 'base/index.html', context)


def about(request):
    return render(request, 'base/about.html')


def contact(request):
    if request.method == "POST":
        contact_form = ContactForm(request.POST)
        if contact_form.is_valid():
            contact_form.save()
            messages.success(request, "Mesajınız başarıyla gönderildi!")
            return redirect('base:contact')
    else:
        contact_form = ContactForm()

    context = {
        'contact_form': contact_form,
    }
    return render(request, 'base/contact.html', context)


def galeries(request):
    
    galeries = Galery.objects.all().order_by('-created_at')
    paginator = Paginator(galeries, 15)
    page_number = request.GET.get('page', 1)
    page_obj = paginator.get_page(page_number)
    
    context = {
        'page_obj': page_obj,
        'galeries' : galeries,
    }
    
    return render(request, 'base/galery.html', context)

def error(request):
    return render(request, 'base/404.html')

templates/partials/_base.html
{% load static %}
{% load i18n %}

<!DOCTYPE html>
<html lang="en">
  <head>
    {% include 'includes/_meta.html' %}

    <title>
      {{ item.title }} |{% block title %}

      {% endblock %}
    </title>

    {% include 'includes/_css.html' %}
  </head>
  <body>
    <main>
      {% include 'partials/_navbar.html' %}

      {% block content %}

      {% endblock %}

      {% include 'partials/_footer.html' %}
    </main>

    {% include 'includes/_js.html' %}
  </body>
</html>

templates/partials/_footer.html
{% load static %}
{% load i18n %}

<footer>
  <div class="gap top-spac70 drk-bg2 remove-bottom">
    <div class="container">
      <div class="footer-data">
        <div class="row">
          <div class="col-md-4 col-sm-12 col-lg-4">
            <div class="wdgt-box">
              <div class="logo">
                <a href="{% url 'base:index' %}" title="Logo"><img src="{{ item.footer_img.url }}" width="100px" style="border-radius: 10px" alt="logo.png" /></a>
              </div>
              <p>{{ item.description|safe }}</p>
            </div>
          </div>
          <div class="col-md-8 col-sm-12 col-lg-8">
            <div class="row justify-content-center">
              <div class="col-md-6 col-sm-4 col-lg-6">
                <div class="wdgt-box">
                  <h4>Sayfalar</h4>
                  <ul>
                    <li>
                      <a href="{% url 'base:about' %}">Hakkımızda</a>
                    </li>
                    <li>
                      <a href="{% url 'article:articles' %}">Makaleler</a>
                    </li>
                    <li>
                      <a href="{% url 'lesson:lessons' %}">Dersler</a>
                    </li>
                    <li>
                      <a href="{% url 'base:galeries' %}">Galeri</a>
                    </li>
                    <li>
                      <a href="{% url 'base:contact' %}">İletişim</a>
                    </li>
                  </ul>
                </div>
              </div>
              <div class="col-md-6 col-sm-4 col-lg-6">
                <div class="wdgt-box">
                  <h4>İletişim</h4>
                  <ul class="cont-lst">
                    <li style="margin-top: 30px;">
                      <i class="flaticon-location-pin"></i>{{ item.address }}
                    </li>
                    <li style="margin-top: 30px;">
                    {% if phones %}
                        {% for phone in phones %}
                            <i class="flaticon-call"></i>
                            <a href="tel:{{ phone.phone_number }}">{{ phone.phone_number }}</a>
                            <br>
                        {% endfor %}
                    {% else %}
                        <i class="flaticon-call"></i>
                        <a href="tel:{{ item.main_phone_number }}">{{ item.main_phone_number }}</a>
                    {% endif %}

                    </li>
                    <li style="margin-top: 30px;">
                      <i class="flaticon-email"></i><a href="mailto:{{ item.email }}">{{ item.email }}</a>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="mb-4">
        <p class="text-center text-white mb-3">
          &copy;
          <span style="color: #ccac48; font-weight: bolder">{{ item.title }}</span>
          <script>
            document.write(new Date().getFullYear())
          </script> Tüm hakları saklıdır.
        </p>

        <div class="scl d-flex justify-content-center">
          
            {% if item.facebook %}
                <a href="{{ item.facebook }}" title="Facebook" target="_blank"><i class="fa fa-facebook"></i></a>
            {% endif %} 
          
            {% if item.instagram %}
                <a href="{{ item.instagram }}" title="Instagram" target="_blank"><i class="fa fa-instagram"></i></a>
            {% endif %} 
          
            {% if item.twitter %}
                <a href="{{ item.twitter }}" title="Twitter" target="_blank"><i class="fa fa-twitter"></i></a>
            {% endif %} 
          
            {% if item.youtube_1 %}
                <a href="{{ item.youtube_1 }}" title="Youtube" target="_blank"><i class="fa fa-youtube"></i></a>
            {% endif %} 
          
            {% if item.youtube_2 %}
                <a href="{{ item.youtube_2 }}" title="Youtube1" target="_blank"><i class="fa fa-youtube"></i></a>
            {% endif %} 
          
            {% if item.youtube_3 %}
                <a href="{{ item.youtube_3 }}" title="Youtube2" target="_blank"><i class="fa fa-youtube"></i></a>
            {% endif %}
        </div>
      </div>
    </div>
  </div>
</footer>

templates/partials/_navbar.html
{% load static %} 
{% load i18n %} 
{% load custom_filters %}

<div class="pageloader-wrap">
  <div class="loader">
    <div class="loader__bar"></div>
    <div class="loader__bar"></div>
    <div class="loader__bar"></div>
    <div class="loader__bar"></div>
    <div class="loader__bar"></div>
    <div class="loader__ball"></div>
  </div>
</div>

<header class="style1">
  <div class="container">
    <div class="logo">
      <a href="{% url 'base:index' %}" title="Logo"><img src="{{ item.navbar_img.url }}" width="60px" style="border-radius: 10px" alt="navbar-logo" /></a>
    </div>
    <nav>
      <div>
        <ul>
          <li class="font-weight-bold">
            <a href="{% url 'base:index' %}" class="{% if request.path == '/' %} activer {% endif %}">Anasayfa</a>
          </li>
          <li class="font-weight-bold">
            <a href="{% url 'base:about' %}" class="{% if request.path == '/hakkimizda/' %} activer {% endif %}">Hakkımızda</a>
          </li>
          <li class="font-weight-bold">
            <a href="{% url 'article:articles' %}" class="{% if request.path|startswith:'/makale/' %} activer {% endif %}">Makale</a>
          </li>
          <li class="font-weight-bold">
            <a href="{% url 'lesson:lessons' %}" class="{% if request.path|startswith:'/ders/' %} activer {% endif %}">Dersler</a>
          </li>
          <li class="font-weight-bold">
            <a href="{% url 'base:galeries' %}" class="{% if request.path == '/galeri/' %} activer {% endif %}">Galeri</a>
          </li>
          <li class="font-weight-bold">
            <a href="{% url 'base:contact' %}" class="{% if request.path == '/iletisim/' %} activer {% endif %}">İletişim</a>
          </li>
        </ul>
      </div>
    </nav>
  </div>
</header>

<div class="rspn-hdr">
  <div class="lg-mn">
    <div class="logo">
      <a href="{% url 'base:index' %}" title="Logo"><img src="{{ item.navbar_img.url }}" width="60px" style="border-radius: 10px" alt="navbar-logo" /></a>
    </div>
    <span class="rspn-mnu-btn"><i class="fa fa-list-ul"></i></span>
  </div>
  <div class="rsnp-mnu">
    <span class="rspn-mnu-cls"><i class="fa fa-times"></i></span>
    <ul>
      <li class="font-weight-bold">
        <a href="{% url 'base:index' %}">Anasayfa</a>
      </li>
      <li class="font-weight-bold">
        <a href="{% url 'base:about' %}">Hakkımızda</a>
      </li>
      <li class="font-weight-bold">
        <a href="{% url 'article:articles' %}">Makale</a>
      </li>
      <li class="font-weight-bold activer">
        <a href="{% url 'lesson:lessons' %}">Dersler</a>
      </li>
      <li class="font-weight-bold">
        <a href="{% url 'base:galeries' %}">Galeri</a>
      </li>
      <li class="font-weight-bold">
        <a href="{% url 'base:contact' %}">İletişim</a>
      </li>
    </ul>
  </div>
</div>