article/urls.py
from django.urls import path
from .views import articles, article_detail, article_by_category, set_language

app_name = 'article'

urlpatterns = [
    path('', articles, name='articles'),
    path('<slug:article_slug>/', article_detail, name='article_detail'),
    path('kategori/<slug:category_slug>', article_by_category, name='article_by_category'),
    path("set_language/<str:language>", set_language, name="set-language"),
]

base/urls.py
from django.urls import path
from .views import index, about, contact, error, galeries

app_name = 'base'

urlpatterns = [
    path('', index, name='index'),
    path('hakkimizda/', about, name='about'),
    path('galeri/', galeries, name='galeries'),
    path('iletisim/', contact, name='contact'),
    path('error/', error, name='error'),
]

core/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from base.views import error

handler = error

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += i18n_patterns(
    path('', include('base.urls', namespace='base')),
    path('makale/', include('article.urls', namespace='article')),
    path('ders/', include('lesson.urls', namespace='lesson')),
    path('rosetta/', include('rosetta.urls')),
    prefix_default_language=False,
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lesson/urls.py
from django.urls import path
from .views import *

app_name = 'lesson'

urlpatterns = [
    path('', lessons, name='lessons'),
    path('<slug:lesson_slug>', lesson_detail, name='lesson_detail'),
]

base/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.utils.text import slugify

class GeneralItem(models.Model):
    title = models.CharField(max_length=100, verbose_name = 'Site Adı')
    description = RichTextField(verbose_name = 'Açıklama')
    email = models.EmailField(verbose_name = 'E-posta')
    address = RichTextField(verbose_name = 'Adres')
    main_phone_number = models.CharField(max_length = 50, verbose_name = 'En çok kullanılan telefon numarası', null=True, blank=True)
    favicon = models.ImageField(upload_to = 'favicon', verbose_name = 'Favicon')
    navbar_img = models.ImageField(upload_to='navbar_img', verbose_name = 'Navbar Resmi')
    footer_img = models.ImageField(upload_to='footer_img', verbose_name = 'Footer Resmi')
    facebook = models.URLField(verbose_name = 'Facebook linki', null=True, blank=True)
    instagram = models.URLField(verbose_name = 'İnstagram linki', null=True, blank=True)
    twitter = models.URLField(verbose_name = 'Twitter linki', null=True, blank=True)
    youtube_1 = models.URLField(verbose_name = 'Youtube birinci linki', null=True, blank=True)
    youtube_2 = models.URLField(verbose_name = 'Youtube ikinci linki', null=True, blank=True)
    youtube_3 = models.URLField(verbose_name = 'Youtube üçüncü linki', null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name = 'Olusturulma Tarihi')
    
    def __str__(self):
        return self.title
    
    class Meta:
        verbose_name_plural = 'Genel Bilgiler'
 

class HomeSlider(models.Model):
    text_arabic = RichTextField(verbose_name = 'Metin (Arapça)')
    text_translation =  RichTextField(verbose_name = 'Metin (Çeviri)')
    source = models.CharField(max_length = 200, verbose_name = 'Kaynak')
    image = models.ImageField(upload_to = 'home_slider', verbose_name = 'Resim')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name = 'Olusturulma Tarihi')
    
    def __str__(self):
        return self.source

    class Meta:
        verbose_name_plural = 'Ana Sayfa Sliderları'



class PageBanner(models.Model):
    title = models.CharField(max_length = 200, verbose_name = 'Banner Baslığı')
    
    about_title = models.CharField(max_length = 200, verbose_name = 'Hakkımızda Banner Başlığı')
    about_img = models.ImageField(upload_to='about_banner_img', verbose_name = 'Hakkımızda Banner Resmi')
    about_arabic_text = RichTextField(verbose_name = 'Hakkımızda Banner Metin (Arapça)')
 
    article_title = models.CharField(max_length = 200, verbose_name = 'Makale Banner Başlığı')
    article_img = models.ImageField(upload_to='article_banner_img', verbose_name = 'Makale Banner Resmi')
    article_arabic_text = RichTextField(verbose_name = 'Makale Banner Metin (Arapça)')
    
    article_category_title = models.CharField(max_length = 200, verbose_name = 'Makale Kategorisi Banner Başlığı')
    article_category_img = models.ImageField(upload_to='article_category_banner_img', verbose_name = 'Makale Kategorisi Banner Resmi')
    article_category_arabic_text = RichTextField(verbose_name = 'Makale Kategorisi Banner Metin (Arapça)')
    
    article_detail_title = models.CharField(max_length = 200, verbose_name = 'Makale Detayları Banner Başlığı')
    article_detail_img = models.ImageField(upload_to='article_detail_banner_img', verbose_name = 'Makale Detayları Banner Resmi')
    article_detail_arabic_text = RichTextField(verbose_name = 'Makale Detayları Banner Metin (Arapça)')

    lesson_title = models.CharField(max_length = 200, verbose_name = 'Ders Banner Başlığı')
    lesson_img = models.ImageField(upload_to='lesson_banner_img', verbose_name = 'Ders Banner Resmi')
    lesson_arabic_text = RichTextField(verbose_name = 'Ders Banner Metin (Arapça)')
    
    lesson_detail_title = models.CharField(max_length = 200, verbose_name = 'Ders Detayları Banner Başlığı')
    lesson_detail_img = models.ImageField(upload_to='lesson_detail_banner_img', verbose_name = 'Ders Detayları Banner Resmi')
    lesson_detail_arabic_text = RichTextField(verbose_name = 'Ders Detayları Banner Metin (Arapça)')
    
    galery_title = models.CharField(max_length = 200, verbose_name = 'Galeri Banner Başlığı')
    galery_img = models.ImageField(upload_to='galery_banner_img', verbose_name = 'Galeri Banner Resmi')
    galery_arabic_text = RichTextField(verbose_name = 'Galeri Banner Metin (Arapça)')
    
    contact_title = models.CharField(max_length = 200, verbose_name = 'İletişim Banner Başlığı')
    contact_img = models.ImageField(upload_to='contact_banner_img', verbose_name = 'İletişim Banner Resmi')
    contact_arabic_text = RichTextField(verbose_name = 'İletişim Banner Metin (Arapça)')
    
    subcsribe_title = models.CharField(max_length = 200, verbose_name = 'Abone Ol Banner Başlığı')
    subcsribe_img = models.ImageField(upload_to='subscribe_banner_img', verbose_name = 'Abone Ol Banner Resmi')
    subcsribe_description = models.TextField(verbose_name = 'Abone Ol Banner Kısa Açıklaması')
    
    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = 'Sayfa Bannerları'
        

class Phone(models.Model):
    title = models.CharField(max_length = 200, verbose_name = 'Telefon Numarası Başlığı')
    phone_number = models.CharField(max_length = 50, verbose_name = 'Telefon numarası')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name = 'Olusturulma Tarihi')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = 'Telefon Numaraları'
        
        
class IslamicConditions(models.Model):
    title = models.CharField(max_length=200, verbose_name = 'Şartın Başlığı')
    description = RichTextField(verbose_name = 'Şartın Açıklaması')
    icon = models.CharField(max_length=200, verbose_name = 'Şartın Simgesi (İkon)')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name = 'Olusturulma Tarihi')
    
    def __str__(self):
        return self.title
    
    class Meta:
        verbose_name_plural = 'İslamın Şartları'
        
        
class About(models.Model):
    title = models.CharField(max_length = 300, verbose_name = 'Hakkımızda Başlığı')
    description = RichTextField(verbose_name = 'Hakkımızda Açıklaması')
    image = models.ImageField(upload_to = 'about', verbose_name = 'Arkaplan Resmi')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name = 'Olusturulma Tarihi')
    
    class Meta:
        verbose_name_plural = 'Hakkımızda'
        
    def __str__(self):
        return self.title
    
class Mission(models.Model):
    title = models.CharField(max_length = 300, verbose_name = 'Görevler Başlığı')
    description = RichTextField(verbose_name = 'Açıklama')
    image = models.ImageField(upload_to = 'mission', verbose_name = 'Resim')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name = 'Olusturulma Tarihi')
    
    def __str__(self):
        return self.title
    
    class Meta:
        verbose_name_plural = 'Görevler'
    
    
class SubMission(models.Model):
    mission = models.ForeignKey(Mission, on_delete = models.CASCADE, verbose_name = 'Görevler', related_name = 'submissions')
    title = models.CharField(max_length = 400, verbose_name = 'Görevler Başlığı')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name = 'Olusturulma Tarihi')
    
    def __str__(self):
        return self.title
    
    class Meta:
        verbose_name_plural = 'Alt Görevler'
        
        
class Subscribe(models.Model):
    email = models.EmailField(verbose_name = 'E-posta')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name = 'Olusturulma Tarihi')

    def __str__(self):
        return self.email

    class Meta:
        verbose_name_plural = 'Aboneler'
        

class Contact(models.Model):
    name = models.CharField(max_length=200, verbose_name='Ad Soyad')
    email = models.EmailField(verbose_name='E-posta')
    phone = models.CharField(max_length=50, verbose_name='Telefon Numarası')
    subject = models.CharField(max_length=300, verbose_name='Konu')
    message = models.TextField(verbose_name='Mesaj')
    is_reply = models.BooleanField(default=False, verbose_name='Cevaplandı mı?', null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Mesaj Geliş Tarihi')
    
    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name_plural = 'İletişim'
        
        
class Galery(models.Model):
    title = models.CharField(max_length = 300, verbose_name = 'Başlık')
    image = models.ImageField(upload_to='images/', verbose_name='Resim')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')
    
    def __str__(self):
        return self.title
    
    class Meta:
        verbose_name_plural = 'Galeri'
        
class MetaTag(models.Model):
    META_NAME_CHOICES = [
        ("author", "Yazar"),
        ("description", "Açıklama"),
        ("keywords", "Anahtar Kelimeler"),
        ("robots", "Robots"),
        ("viewport", "Viewport"),
        ("og:title", "Open Graph Başlığı"),
        ("og:description", "Open Graph Açıklaması"),
        ("og:image", "Open Graph Görseli"),
        ("twitter:title", "Twitter Başlığı"),
        ("twitter:description", "Twitter Açıklaması"),
        ("twitter:image", "Twitter Görseli"),
    ]
    
    page_name = models.CharField(max_length=255, help_text="Ana sayfa için boş bırakınız. Sayfa adı (örnek: Hakkımızda, Servis, Blog, Galeri, İletişim)", blank=True, null=True)
    slug = models.SlugField(blank=True, null=True)
    name = models.CharField(max_length=50, choices=META_NAME_CHOICES, help_text="Meta adı veya özelliği")
    content = models.TextField(help_text="Meta tag içeriği (content)")
    
    def save(self, *args, **kwargs):
        if not self.page_name:
            self.slug = ""
        if not self.slug or self.slug != slugify(self.page_name):

base/forms.py
from django import forms
from .models import Subscribe
from .models import Contact

class SubscribeForm(forms.ModelForm):
    class Meta:
        model = Subscribe
        fields = ['email']
        widgets = {
            "email": forms.EmailInput(
                attrs={
                    "placeholder": "Mail Adresinizi Girin",
                }
            )
        }

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['name', 'email', 'phone', 'subject', 'message']
        widgets = {
            'name': forms.TextInput(attrs={
                'placeholder': 'İsim ve Soyisminiz',
                'class': 'form-control mb-3'
            }),
            'email': forms.EmailInput(attrs={
                'placeholder': 'Mail Adresiniz',
                'class': 'form-control mb-3'
            }),
            'phone': forms.TextInput(attrs={
                'placeholder': 'Telefon Numarası',
                'class': 'form-control mb-3 phone-mask',
            }),
            'subject': forms.TextInput(attrs={
                'placeholder': 'Mesajın Konusu',
                'class': 'form-control mb-3'
            }),
            'message': forms.Textarea(attrs={
                'placeholder': 'Mesajınız',
                'class': 'form-control mb-3'
            })
        }

base/views.py
from django.shortcuts import render
from .forms import SubscribeForm, ContactForm
from django.shortcuts import redirect
from django.contrib import messages
from .models import Galery
from django.core.paginator import Paginator

def index(request):
    
    if request.method == "POST":
        form = SubscribeForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Başarıyla abone olundu!!!")
            return redirect('base:index')
    else:
        form = SubscribeForm()
        
    context = {
        'form' : form
    }
    
    return render(request, 'base/index.html', context)


def about(request):
    return render(request, 'base/about.html')


def contact(request):
    if request.method == "POST":
        contact_form = ContactForm(request.POST)
        if contact_form.is_valid():
            contact_form.save()
            messages.success(request, "Mesajınız başarıyla gönderildi!")
            return redirect('base:contact')
    else:
        contact_form = ContactForm()

    context = {
        'contact_form': contact_form,
    }
    return render(request, 'base/contact.html', context)


def galeries(request):
    
    galeries = Galery.objects.all().order_by('-created_at')
    paginator = Paginator(galeries, 15)
    page_number = request.GET.get('page', 1)
    page_obj = paginator.get_page(page_number)
    
    context = {
        'page_obj': page_obj,
        'galeries' : galeries,
    }
    
    return render(request, 'base/galery.html', context)

def error(request):
    return render(request, 'base/404.html')

templates/base/about.html
{% extends 'partials/_base.html' %} 
{% load static %} 
{% load i18n %} 

{% block title %} Hakkımızda {% endblock %}

{% block content %}
  <section>
    <div class="gap remove-bottom black-layer2 opc85">
      <div class="fixed-bg" style="background-image: url({{ banner.about_img.url }})"></div>
      <div class="container">
        <div class="page-title-wrap">
          <h1 style="color: white;">{{ banner.about_arabic_text|safe }}</h1>
          <h2>{{ banner.about_title }}</h2>
          <ul class="breadcrumbs">
            <li>
              <a href="{% url 'base:index' %}">Anasayfa</a>
            </li>
            <li>{{ banner.about_title }}</li>
          </ul>
        </div>
      </div>
    </div>
  </section>

  <section>
    <div class="gap">
      <div class="container">
        <div class="sec-title style2 text-center">
          <div class="sec-title-inner mb-3">
            <h3><span class="secndry-clr">{{ about.title }}</span></h3>
          </div>
          <p>{{ about.description|safe }}</p>
        </div>
      </div>
    </div>
  </section>

  <section>
    <div class="gap gray-bg2">
      <div class="container">
        <div class="msn-wrap">
          <div class="row">
            <div class="col-md-6 col-sm-12 col-lg-6">
              <div class="msn-thmb-wrap">
                <a href="{{ mission.image.url }}" data-fancybox="gallery"><img src="{{ mission.image.url }}" alt="msn-img1.jpg" /></a>
              </div>
            </div>
            <div class="col-md-6 col-sm-12 col-lg-6 mt-5">
              <div class="msn-desc">
                <h3>{{ mission.title }}</h3>
                <p>{{ mission.description|safe }}</p>
                <ul>
                  {% for item in mission.submissions.all %}
                    <li>{{ item.title }}</li>
                  {% endfor %}
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

templates/base/contact.html
{% extends 'partials/_base.html' %} 
{% load static %} 
{% load i18n %} 

{% block title %}
  İletişim
{% endblock %} 

{% block content %}
  <section>
    <div class="gap remove-bottom black-layer2 opc85">
      <div class="fixed-bg" style="background-image: url({{ banner.contact_img.url }})"></div>
      <div class="container">
        <div class="page-title-wrap">
          <h1 style="color: white;">{{ banner.contact_arabic_text|safe }}</h1>
          <h2>{{ banner.contact_title }}</h2>
          <ul class="breadcrumbs">
            <li>
              <a href="{% url 'base:index' %}">Anasayfa</a>
            </li>
            <li>{{ banner.contact_title }}</li>
          </ul>
        </div>
      </div>
    </div>
  </section>

  <section>
    <div class="gap">
      <div class="container">
        <div class="sec-title text-center">
          <div class="sec-title-inner">
            <span>Bilgi Alın</span>
            <h3>İletişim Bilgileri</h3>
          </div>
        </div>
        <div class="contact-info-wrap text-center remove-ext3">
          <div class="row">
            <div class="col-md-4 col-sm-6 col-lg-4">
              <div class="contact-info-box" style="height: 250px">
                <i class="flaticon-location-pin"></i>
                <strong>Adres</strong>
                <span>{{ item.address }}</span>
              </div>
            </div>
            <div class="col-md-4 col-sm-6 col-lg-4">
              <div class="contact-info-box" style="height: 250px">
                <i class="flaticon-call"></i>
                <strong>Telefon Numaraları</strong>
                {% if phones %}
                  {% for phone in phones %}
                    <span>{{ phone.title }}: {{ phone.phone_number }}</span>
                  {% endfor %}
                {% else %}
                  <span>{{ item.main_phone_number }}</span>
                {% endif %}
              </div>
            </div>
            <div class="col-md-4 col-sm-6 col-lg-4">
              <div class="contact-info-box" style="height: 250px">
                <i class="flaticon-email"></i>
                <strong>Email</strong>
                <a href="mailto:{{ item.email }}">{{ item.email }}</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <section class="mb-5">
    <div class="gap no-gap">
      <div class="container">
        <div class="sec-title text-center">
          <div class="sec-title-inner">
            <span>Sorunuzmu var?</span>
            <h3>Mesaj Gönderin</h3>
          </div>
        </div>
        <div class="contact-form text-center">
          {% if messages %}
            {% for message in messages %}
                <div style=" background-color: #000; color: #cfaf4c; padding: 10px; border-radius: 10px; margin-bottom: 10px; border: 1px solid #000;" role="alert"> {{ message }}</div>
            {% endfor %}
          {% endif %}
          <form method="post" action="{% url 'base:contact' %}">
            {% csrf_token %}
            <div class="row mrg20">
              <div class="col-md-6 col-sm-6 col-lg-6">{{ contact_form.name }}</div>
              <div class="col-md-6 col-sm-6 col-lg-6">{{ contact_form.email }}</div>
              <div class="col-md-6 col-sm-6 col-lg-6">{{ contact_form.phone }}</div>
              <div class="col-md-6 col-sm-6 col-lg-6">{{ contact_form.subject }}</div>
              <div class="col-md-12 col-sm-12 col-lg-12"> {{ contact_form.message }}
                <button class="thm-btn brd-rd40" type="submit">Bize Ulaşın</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </section>
  
{% endblock %}

templates/base/galery.html
{% extends 'partials/_base.html' %} 
{% load static %} 
{% load i18n %} 
{% block title %}
  Galeri
{% endblock %} 

{% block content %}
  <section>
    <div class="gap remove-bottom black-layer2 opc85">
      <div class="fixed-bg" style="background-image: url({{ banner.galery_img.url }})"></div>
      <div class="container">
        <div class="page-title-wrap">
          <h1 style="color: white;">{{ banner.galery_arabic_text|safe }}</h1>
          <h2>{{ banner.galery_title }}</h2>
          <ul class="breadcrumbs">
            <li>
              <a href="{% url 'base:index' %}">Anasayfa</a>
            </li>
            <li>{{ banner.galery_title }}</li>
          </ul>
        </div>
      </div>
    </div>
  </section>

  <section>
    <div class="gap">
      <div class="container">
        <div class="prtfl-wrap text-center">
          <div class="prtfl-dta remove-ext1">
            <div class="row mrg15 masonry">
              {% if page_obj %}
                {% for image in page_obj %}
                  <div class="col-md-4 col-sm-6 col-lg-4 fltr-itm fltr-itm1">
                    <div class="prtfl-box">
                      <img src="{{ image.image.url }}" alt="{{ image.title }}" style="height: 350px" />
                      <div class="prtfl-info">
                        <a href="{{ image.image.url }}" data-fancybox="gallery"><i class="fa fa-plus text-warning" style="font-size: 40px"></i></a>
                      </div>
                    </div>
                  </div>
                {% endfor %}
              {% else %}
                <div class="alert alert-warning" role="alert" style="background-color: #FFF3CD; color: #856404; border: 1px solid #ffeeba; padding: 15px; border-radius: 5px; font-size: 16px; display: flex; align-items: center; justify-content: center; box-shadow: 0 2px 5px rgba(0,0,0,0.1);">
                    <i class="fa fa-exclamation-circle" style="margin-right: 10px; font-size: 20px;"></i> 
                    Henüz resim ilave olunmayıb
                </div>
              {% endif %}
            </div>
          </div>
        </div>

        <div class="pagination-wrap text-center">
          <ul class="pagination">
            {% if page_obj.has_previous %}
              <li>
                <a href="?page={{ page_obj.previous_page_number }}" title="Previous">&laquo;</a>
              </li>
            {% else %}
              <li class="disabled">
                <a href="" title="Previous">&laquo;</a>
              </li>
            {% endif %} {% for num in page_obj.paginator.page_range %}
              {% if num == page_obj.number %}
                <li class="active">
                  <a href="" title="Page {{ num }}">{{ num }}</a>
                </li>
              {% elif num >= page_obj.number|add:'-2' and num <= page_obj.number|add:'2' %}
                <li>
                  <a href="?page={{ num }}" title="Page {{ num }}">{{ num }}</a>
                </li>
              {% endif %}
            {% endfor %} {% if page_obj.has_next %}
              <li>
                <a href="?page={{ page_obj.next_page_number }}" title="Next">&raquo;</a>
              </li>
            {% else %}
              <li class="disabled">
                <a href="" title="Next">&raquo;</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

templates/base/index.html
{% extends 'partials/_base.html' %} 
{% load static %} 
{% load i18n %} 

{% block title %} Ana Sayfa {% endblock %} 

{% block content %}

  <section style="border-bottom: 3px solid #E8C960;">
    <div class="gap no-gap owl-yellow">
      <div class="featured-area-wrap text-center">
        <div class="featured-area owl-carousel">
            {% for slider in home_sliders %}
                <div class="featured-item" style="height: 100vh; background-image: url({{ slider.image.url }}); padding: 130px 15px 90px 15px;">
                    <div class="featured-cap" style="padding: 30px 0 100px 0;">
                    <h1 style="color: #E8C960; margin-bottom: 30px;">بِسْمِ اللَّهِ الرَّحْمٰنِ الرَّحِيمِ </h1>
                    <h2 style="color: white; margin-bottom: 30px;">{{ slider.text_arabic|safe }}</h2>
                    <h3> {{ slider.text_translation|safe }}</h3>
                    <span>{{ slider.source }}</span>
                    <a class="thm-btn brd-rd40" href="{% url 'lesson:lessons' %}">Daha Fazla</a>
                    </div>
                </div>
            {% endfor %}
        </div>
      </div>
    </div>
  </section>

  <section style="border-bottom: 1px solid #E8C960;">
    <div class="gap" style="padding: 60px 0;">
      <div class="lft-shp shp-lyr"></div>
      <div class="container">
        <div class="plrs-wrap text-center remove-ext5">
          <div class="row">
            {% for condition in conditions %}
                {% if forloop.first %}
                    <div class="col-md-12 col-sm-12 col-lg-12">
                {% else %}
                    <div class="col-md-3 col-sm-6 col-lg-3">
                {% endif %}
                    <div class="plr-box">
                    <i class="{{ condition.icon }}"></i>
                    <div class="pilr-info">
                        <h4>{{ condition.title }}</h4>
                        <p>{{ condition.description|safe }}</p>
                    </div>
                    </div>
                </div>
            {% endfor %}

          </div>
        </div>
      </div>
    </div>
  </section>

  <section style="border-bottom: 1px solid #E8C960;">
    <div class="gap white-grad-layer">
      <div class="fixed-bg" style="background-image: url({{ about.image.url }})"></div>
      <div class="container">
        <div class="abot-wrap">
          <div class="row">
            <div class="col-md-6 col-sm-12 col-lg-6">
              <div class="abot-sec">
                <div class="sec-title">
                  <div class="sec-title-inner">
                    <span>Hakkımızda</span>
                    <h3>{{ about.title }}</h3>
                  </div>
                </div>
                <p>{{ about.description|safe|truncatewords:70 }}</p>
                <a class="thm-btn brd-rd40" href="{% url 'base:about' %}">Daha Fazla</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <section>
    <div class="my-5">
      <div class="container">
        <div class="blog-wrap remove-ext7">
            <h2 class="text-center my-5" style="color: #D1AC3C;">Makaleler</h2>
            <div class="row mrg40">
                {% for article in last_6_articles %}
                    <div class="col-md-4 col-sm-6 col-lg-4 fadeIn" data-wow-duration=".8s" data-wow-delay=".{{ forloop.counter|floatformat:1 }}s">
                        <div class="blog-box">
                            <div class="blog-thmb">
                                <a href="{% url 'article:article_detail' article.slug %}">
                                    <img src="{{ article.image.url }}" style="height: 250px;" alt="{{ article.title }}" />
                                </a>
                            </div>
                            <div class="blog-info">
                                <ul class="pst-mta2">
                                    <li>
                                        <a href="{% url 'article:article_by_category' article.category.slug %}">{{ article.category }}</a>
                                    </li>
                                </ul>
                                <h4><a href="{% url 'article:article_detail' article.slug %}">{{ article.title }}</a></h4>
                                <p>{{ article.description|safe|truncatewords:20 }}</p>
                                <a href="{% url 'article:article_detail' article.slug %}">Daha Fazla Oku</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}

            </div>
          <div class="d-flex justify-content-center">
            <a class="thm-btn brd-rd40" href="{% url 'article:articles' %}">Daha Fazlası...</a>
          </div>
        </div>
      </div>
    </div>
  </section>

  <section class="mt-5">
    <div class="gap thm-layer opc9 mt-5">
      <div class="fixed-bg" style="background-image: url({{ banner.subcsribe_img.url }})"></div>
      <div class="container">
        <div class="nwsltr-wrp text-center">
          <div class="nwsltr-innr">
            <div class="mb-3">
                {% if messages %}
                    {% for message in messages %}
                        <div style="background-color: #000; color: #CFAF4C; padding: 10px; border-radius: 10px; margin-bottom: 10px; border: 1px solid #000;" role="alert">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
            </div>

            <div class="nwsltr-title">
              <h3>{{ banner.subcsribe_title }}</h3>
              <span>{{ banner.subcsribe_description }}</span>
            </div>
            <form action="{% url 'base:index' %}" method="post">
              {% csrf_token %}
              {{ form.email }}
              <button type="submit">Abone Ol</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </section>

{% endblock %}